config/routes.rb
Sleuth::Application.routes.draw do
  root "home#index"

  get 'cartridge/search'  => 'cartridge#search'
  post 'cartridge/import' => 'cartridge#import'

  resources :cartridge

  

end

app/models/cartridge.rb
class Cartridge < ActiveRecord::Base
  has_many :cartridge_pages
end

app/models/cartridge_page.rb
class CartridgePage < ActiveRecord::Base
  belongs_to :cartridge
  has_and_belongs_to_many :page_tags
end

app/models/cartridge_page_page_tag.rb
class CartridgePagePageTag < ActiveRecord::Base
  belongs_to :page_tag
  belongs_to :cartridge_page
end

app/models/page_tag.rb
class PageTag < ActiveRecord::Base
  has_and_belongs_to_many :cartridge_pages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cartridge_controller.rb
class CartridgeController < ApplicationController
  require "#{Rails.root}/lib/uploader"
  respond_to :json
  layout "navigation"

  def index
    @cartridges = Cartridge.all
  end

  def show
    @cartridge = Cartridge.find params[:id]
  end

  def create
  end

  def search
    cartridge_pages = CartridgePage.joins(:page_tags).joins(:cartridge).
      where(page_tags: {name: params[:text]}).order("cartridges.name, page_num")

    @search_results = cartridge_pages.inject({}) do |memo, cp|
      memo[cp.cartridge.name] ||= []
      unless memo[cp.cartridge.name].include?({ page: cp.page_num, tags: cp.page_tags.map(&:name) })
        memo[cp.cartridge.name].push({ page: cp.page_num, tags: cp.page_tags.map(&:name) })
      end
      memo
    end
    @search_results
  end

  def import
    uploader = Sleuth::Uploader.new(params[:datafile])
    uploader.write
    uploader.save

    redirect_to action: "index"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartridge_helper.rb
module CartridgeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cartridge/index.html.erb
<% if @cartridges.length == 0 %>
  <h3>No search results found</h3>
<% end %>

<% @cartridges.each_with_index do |value, index| %>
  <% if (index + 1) % 2 != 0 %>
    <div class="row">
  <% end %>
    <div class="col-md-6">
      <% pngs = ["Create A Critter", "Ashlyns Alphabet", "Best Of Pixar", "Cricut Essentials"] %>
      <% if pngs.include? value[:name] %>
        <%= link_to image_tag(value[:name].gsub(" ", "") + '_FrontCover.PNG', class: "page-img"),
                    cartridge_path(value[:id]) %>
      <% else %>
        <%= link_to image_tag(value[:name].gsub(" ", "") + '_FrontCover.JPG', class: "page-img"),
                    cartridge_path(value[:id])%>
      <% end %>
    </div>
  <% if (index + 1) % 2 == 0 %>
    </div>
  <% end %>
<% end %>

app/views/cartridge/search.html.erb
<% if @search_results.length == 0 %>
  <h3>No search results found</h3>
<% end %>

<% @search_results.each do |key, value| %>
  <div class="cartridge">
    <h3><%= key %></h3>
    <hr />
      <% value.each_with_index do |val, index| %>
        <% if (index + 1) % 2 != 0 %>
          <div class="row">
        <% end %>
          <div class="col-md-6">
            <% val[:tags].each do |tag| %>
            <div class="label label-default"><%= tag %></div>
            <% end %>
            <% pngs = ["Create A Critter", "Ashlyns Alphabet", "Best Of Pixar", "Cricut Essentials"] %>
            <% if pngs.include? key %>
            
              <%= image_tag(key.gsub(" ", "") + '_page' + val[:page].to_s + '.PNG', 
                            class: "page-img", title: val[:page].to_s) %>
            <% else %>
              <%= image_tag(key.gsub(" ", "") + '_page' + val[:page].to_s + '.JPG', 
                            class: "page-img", title: val[:page].to_s) %>
            <% end %>
          </div>
        <% if (index + 1) % 2 == 0 %>
          </div>
        <% end %>
      <% end %>
    </div>
<% end %>

app/views/cartridge/show.html.erb
<div class="cartridge">
  <h3><%= @cartridge.name %></h3>
  <hr />
    <% @cartridge.cartridge_pages.sort.each_with_index do |val, index| %>
      <% if (index + 1) % 2 != 0 %>
        <div class="row">
      <% end %>
      <div class="col-md-6">
        <% pngs = ["Create A Critter", "Ashlyns Alphabet", "Best Of Pixar", "Cricut Essentials"] %>
        <% if pngs.include? @cartridge.name %>
          <%= image_tag(@cartridge.name.gsub(" ", "") + '_page' + val[:page_num].to_s + '.PNG', class: "page-img") %>
        <% else %>
          <%= image_tag(@cartridge.name.gsub(" ", "") + '_page' + val[:page_num].to_s + '.JPG', class: "page-img") %>
        <% end %>
      </div>
      <% if (index + 1) % 2 == 0 %>
        </div>
      <% end %>
    <% end %>
</div>

app/views/home/index.html.erb
<div class="row header-section">
  <div class="col-md-7 col-md-offset-2">
    <h1 class="header">Cartridge Sleuth</h1>
    <%= image_tag "magifying_glass.jpg", class: "magnifying-glass-img" %>
  </div>
</div>

<hr class="featurette-divider" />

<div class="row featurette">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag({controller: "cartridge", action: "search"}, method: "get", class: "inline-form")  do %>
      <%= text_field_tag :text, nil, {class: "search-box", placeholder: "Search"} %>
      <%= submit_tag "Search", class: "btn btn-primary search-button" %>
    <% end %>
  </div>
</div>

<hr class="featurette-divider" />

<div class="row featurette">
  <a href=<%= cartridge_index_path %> >
    <div class="col-md-4 col-md-offset-2 list-cartridges">
      <h2 class="featurette-heading">
        List all Cartridges
      </h2>
      <span class="list-icon glyphicon glyphicon-th"></span>
    </div>
  </a>

  <div class="col-md-4 upload-file" data-toggle="modal" data-target="#upload-modal">
    <h2 class="featurette-heading">
      Upload CSV File
    </h2>
    <span class="upload-icon glyphicon glyphicon-upload"></span>
  </div>

</div>

<!-- Modal -->
<div class="modal fade" id="upload-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Upload CSV File</h4>
      </div>
      <div class="modal-body">
        <button class="browse-button btn btn-primary">Browse</button>
        <label id="filename"></label>
        <input id="file-input" class="hidden" type="file" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Upload</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("button.browse-button").on("click", function(ev) { $("#file-input").click(); });
  $("label#filename").on("click", function(ev) { $("#file-input").click(); });
  $("#file-input").on("change", function(ev) { $("#filename").html($(ev.currentTarget).val()); });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sleuth</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/navigation.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cartridge Sleuth</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">Cartridge Sleuth</a>
      </div>
      <%= form_tag({controller: "cartridge", action: "search"}, method: "get", class: "navbar-form navbar-left navbar-search")  do %>
        <%= text_field_tag :text, nil, {class: "navbar-search-box", placeholder: "Search"} %>
        <%= submit_tag "Search", class: "btn btn-primary search-button" %>
      <% end %>

      <%= form_tag({controller: "cartridge", action: "import"}, multipart: true, class: "navbar-form navbar-right navbar-import")  do %>
        <%= file_field_tag 'datafile', class: "import-field" %>
        <%= submit_tag "Import", class: "btn btn-primary import-button" %>
      <% end %>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>